
def exception_callback(ex, gaerman_worker=None):
    print ex
